name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: library_db_test
          POSTGRES_USER: library_user
          POSTGRES_PASSWORD: library_pass123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U library_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r django/requirements.txt

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://library_user:library_pass123@localhost:5432/library_db_test" >> $GITHUB_ENV
          echo "DJANGO_SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV
          echo "DJANGO_DEBUG=True" >> $GITHUB_ENV

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -U library_user; then
              echo "PostgreSQL is ready!"
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: Run migrations
        working-directory: ./django
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        working-directory: ./django
        run: |
          python manage.py test --verbosity=2
